# syntax=docker/dockerfile:1

FROM golang:1.22.1 AS build-stage

WORKDIR /app

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -C ./cmd/custom-back/ -o /app/bin/main

FROM gcr.io/distroless/base-debian12 AS build-release-stage

WORKDIR /app

COPY --from=build-stage /app/bin/main /app/bin/main

EXPOSE 8080 1002

ENTRYPOINT ["/app/bin/main"]
