package handlers

type CHAT_HEADERS = byte

const (
	CHAT_EVENT CHAT_HEADERS = iota
	MESSAGE_SENT
	SCROLL_REQUEST
	MESSAGE_SAVE_ERROR
	CHAT_SCROLL_DONE
	NOTIFICATIONS
	CHAT_CONN_REQ
	CHAT_DISC_REQ
	BOOSTS_REQ
	CHAT_EVENT_FROM_SCROLL

	BOOST_EVENT       = CHAT_HEADERS(0xAA)
	BOOST_SCROLL_DONE = CHAT_HEADERS(0xAB)

	ROOT_ERROR     = CHAT_HEADERS(0xBB)
	NEW_ROOT_PLACE = CHAT_HEADERS(0xBA)
)
